### ISSUE TITLE
Test Site

### ISSUE THREAD

**Issue by bazuccka** [bazuccka/quizlet#4]
Check for bugs, irregularities, anything. If you see something weird take a screenshot and open a new issue per issue.

**Comment by bazuccka** [comment]
@BryanSHoyt test as well

**Comment by BryanSHoyt** [comment]
tested on non-ITT computer . must use the default browser for your computer unless you designated which browser to use when you installed wamp server.

**Comment by BryanSHoyt** [comment]
Question # 28 answer should be the USA and Canada.
